set nocompatible

"Plugins
call plug#begin('~/.vim/plugged')
    Plug 'dylanaraps/wal' "wal colorscheme
    Plug 'itchyny/lightline.vim' "lightline
    Plug 'scrooloose/nerdtree' "file tree view
    Plug 'tpope/vim-eunuch' "inclusion of core Unix commands
    Plug 'ervandew/supertab' "tab completion
    Plug 'terryma/vim-multiple-cursors' "multiple cursors
    Plug 'tpope/vim-surround' "editing brackets etc.
    Plug 'mattn/emmet-vim' "completion tool for HTML, CSS, JavaScript
    Plug 'w0rp/ale' "Lint engine

    "Plug 'jiangmiao/auto-pairs' "pairing paranthesese
call plug#end()


"Colors
colorscheme snazzy
syntax enable
autocmd FileType html set omnifunc=htmlcomplete#CompleteTags
set laststatus=2
let g:lightline = {'colorscheme': 'jellybeans'}

"Tabs & Spaces
set expandtab    "tabs are spaces
set tabstop=4    "number of visual spaces per tab
set softtabstop=4    "number of spaces in tab when editing
set backspace=2 "make backspace work like most other programs
set shiftround
set shiftwidth=4

"UI Config
set noshowmode "lightline already shows stuff
set number    "show line numbers
set relativenumber    "show numbers relative to current line
set ruler  " show cursor position   
set showcmd    "show last command in bottom bar
set cursorline    "highlight current lin
filetype indent on    "load filetype-specific indent file
set wildmenu    "visual autocomplete for command menu
set lazyredraw
set showmatch   "highlight matching brackets

"Search
set incsearch    "search as characters are entered
set hlsearch
set path +=**    "Provides tab-completion for all file-related tasks

"Mapping
inoremap kj <esc>
vnoremap kj <esc>
map <C-o> :NERDTreeToggle<CR>

"Linter
let b:ale_fixers = ['eslint']
let b:ale_fix_on_save = 1
