IDE:
  mainWindow:
    detached: !QVariantMap
      documents-dock: ""
      help-dock: ""
      post-dock: ""
    geometry: AdnQywACAAAAAAAAAAAAOAAACf8AAAWfAAAAAAAAADgAAAn/AAAFnwAAAAAAAAAACgA=
    state: AAAA/wAAAAD9AAAAAgAAAAAAAAAAAAAAAPwCAAAAAfsAAAAcAGQAbwBjAHUAbQBlAG4AdABzAC0AZABvAGMAawAAAAAA/////wAAAIYA////AAAAAQAABAAAAAUs/AIAAAAC+wAAABIAaABlAGwAcAAtAGQAbwBjAGsBAAAAGwAAA5MAAABSAP////sAAAASAHAAbwBzAHQALQBkAG8AYwBrAQAAA68AAAGYAAAAUgD///8AAAX/AAAFLAAAAAEAAAACAAAAAQAAAAL8AAAAAA==
  postWindow:
    lineWrap: false
  recentDocuments: !QVariantList
    []